apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-proj-app
  labels:
    app: mini-proj-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mini-proj-app
  template:
    metadata:
      labels:
        app: mini-proj-app
    spec:
      containers:
      - name: shift-sched-container
        image: docker.io/library/mini-proj
        ports:
        - containerPort: 80
